const types = {
  CHANGE_BUDGET: 'CHANGE_BUDGET',
  SUBMIT_BUDGET: 'SUBMIT_BUDGET',

  CHANGE_EXPENSE_VALUE: 'CHANGE_EXPENSE_VALUE',
  CHANGE_EXPENSE_NAME: 'CHANGE_EXPENSE_NAME',
  ADD_EXPENSE: 'ADD_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
};
